name: Build AppImage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Build docker image that produces the AppImage
        run: |
          export REF=${GITHUB_REF#refs/*/}
          docker build -t xenial-appimage -f docker/xenial-appimage/Dockerfile .
          id=$(docker create --privileged xenial-appimage)
          docker start --attach $id
          docker cp $id:/yubioath-desktop/Yubico_Authenticator-x86_64.AppImage yubioath-desktop-${REF}.AppImage

      - name: Push artifact to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export REF=${GITHUB_REF#refs/*/}
          aws s3 mv yubioath-desktop-${REF}.AppImage s3://yubico-builds/yubioath-desktop/yubioath-desktop-${REF}.AppImage --acl public-read
